### ISSUE TITLE
延时调用，出现没有图片

### ISSUE THREAD

**Issue by biluochun** [hilongjw/vue-lazyload#108]
when use `setTimeout` / `await` get some bug.  
demo: [http://runjs.cn/code/z2dl4pnz](http://runjs.cn/code/z2dl4pnz)

**Comment by cwcw2424** [comment]
runjs: http://runjs.cn/code/z2dl4pnz

Probably imitate the environment I wrote this demo, plus setTimeout when the problem (because I used the environment async / await this problem)

Demo and their environment breakpoint update and add

1.My environment has not been updated in the update,
2.Runjs will break every click in the update
(This difference I am very confused, with the above problem I do not know if it does not matter, because after adding setTimeout, the breakpoint is still broken, but no picture.

**Comment by biluochun** [comment]
get it. Thanks.  
will `lazyLoadHandler`  add to `README.md` ?

**Comment by hilongjw** [comment]
@biluochun sure, I've updated
